# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eccd2b6ad05a7024749b7271d64ed65e"
name = "ai-content-generator"
handle = "ai-content-generator-5"
application_url = "https://shpify-ai-content-generator.onrender.com"
embedded = true

[build]
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://shpify-ai-content-generator.onrender.com/auth/callback",
  "https://shpify-ai-content-generator.onrender.com/auth/shopify/callback",
  "https://shpify-ai-content-generator.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
